name: Publish to PyPI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    name: wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.9
      - name: build
        shell: bash
        run: |
          uv build --wheel
          uvx wheel tags --remove --abi-tag none --python-tag py3 dist/*.whl
      - if: ${{ runner.os }} == 'macOS'
        run: uvx wheel tags --remove --platform-tag macosx_10_9_x86_64 dist/*.whl

      - name: Upload wheels artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}-${{ runner.arch }}
          path: ./dist/*.whl

  publish:
    name: Publish to PyPI
    needs: [build-wheels]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: 🚢 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "./dist/*"
